name: demo-data-source
language: Python
variables:
  - name: output
    inputType: OutputTopic
    defaultValue: phishing-data
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
